const data = {
  "events": [{
    "id": 3555240,
    "permalink": "/events/2015/2/21/illy",
    "presented_by": null,
    "title": "Illy",
    "description": null,
    "excerpt": null,
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T19:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T19:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1421122078/event-3555240.png", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3555240",
      "hover": "/t/h/e/3555240",
      "click": "/t/c/e/3555240/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3555240"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3555240",
      "hover": "https://t.dostuffmedia.com/t/h/e/3555240",
      "click": "https://t.dostuffmedia.com/t/c/e/3555240/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3555240"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17287,
      "title": "Fortune Sound Club",
      "permalink": "/venues/fortune-sound-club",
      "latitude": 49.28052839999999,
      "longitude": -123.1007512,
      "popularity": 50.0,
      "address": "147 Pender Street East",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V6A1T6",
      "full_address": "147 Pender Street East, Vancouver, BC, V6A1T6",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3574484,
    "permalink": "/events/2015/2/21/rory-scovel",
    "presented_by": null,
    "title": "Rory Scovel",
    "description": "Doors open: 19:00",
    "excerpt": "Doors open: 19:00",
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T19:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T19:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "CA$19.00",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1421421569/event-3574484.png", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3574484",
      "hover": "/t/h/e/3574484",
      "click": "/t/c/e/3574484/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3574484"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3574484",
      "hover": "https://t.dostuffmedia.com/t/h/e/3574484",
      "click": "https://t.dostuffmedia.com/t/c/e/3574484/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3574484"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17260,
      "title": "Biltmore Cabaret",
      "permalink": "/venues/biltmore-cabaret",
      "latitude": 49.2604058,
      "longitude": -123.0966757,
      "popularity": 50.0,
      "address": "2755 Prince Edward St",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V5T 0A9",
      "full_address": "2755 Prince Edward St, Vancouver, BC, V5T 0A9",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3610748,
    "permalink": "/events/2015/2/21/the-pistolwhips",
    "presented_by": null,
    "title": "The Pistolwhips",
    "description": null,
    "excerpt": null,
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T19:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T19:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1499208456/metro-bkg_1-32.jpg", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3610748",
      "hover": "/t/h/e/3610748",
      "click": "/t/c/e/3610748/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3610748"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3610748",
      "hover": "https://t.dostuffmedia.com/t/h/e/3610748",
      "click": "https://t.dostuffmedia.com/t/c/e/3610748/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3610748"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17264,
      "title": "The Media Club",
      "permalink": "/venues/the-media-club",
      "latitude": 49.2797507,
      "longitude": -123.113122,
      "popularity": 7.0,
      "address": "695 Cambie Street",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V6B2P1",
      "full_address": "695 Cambie Street, Vancouver, BC, V6B2P1",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3259563,
    "permalink": "/events/2015/2/21/cold-war-kids",
    "presented_by": null,
    "title": "Cold War Kids",
    "description": "Doors open: 20:00",
    "excerpt": "Doors open: 20:00",
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T20:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T20:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "From CA$69.95",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1414273754/event-3259563.png", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3259563",
      "hover": "/t/h/e/3259563",
      "click": "/t/c/e/3259563/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3259563"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3259563",
      "hover": "https://t.dostuffmedia.com/t/h/e/3259563",
      "click": "https://t.dostuffmedia.com/t/c/e/3259563/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3259563"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17261,
      "title": "Commodore Ballroom",
      "permalink": "/venues/commodore-ballroom",
      "latitude": 49.2805555,
      "longitude": -123.1207453,
      "popularity": 40.0,
      "address": "868 Granville Street",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V6Z 1K3",
      "full_address": "868 Granville Street, Vancouver, BC, V6Z 1K3",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3620104,
    "permalink": "/events/2015/2/21/omar-linx",
    "presented_by": null,
    "title": "Omar Linx",
    "description": "Doors open: 20:00",
    "excerpt": "Doors open: 20:00",
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T20:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T20:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1499208456/metro-bkg_1-32.jpg", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3620104",
      "hover": "/t/h/e/3620104",
      "click": "/t/c/e/3620104/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3620104"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3620104",
      "hover": "https://t.dostuffmedia.com/t/h/e/3620104",
      "click": "https://t.dostuffmedia.com/t/c/e/3620104/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3620104"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17265,
      "title": "Venue",
      "permalink": "/venues/venue",
      "latitude": 49.28075140000001,
      "longitude": -123.1214697,
      "popularity": 40.0,
      "address": "881 Granville St",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V6Z 1K7",
      "full_address": "881 Granville St, Vancouver, BC, V6Z 1K7",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3353449,
    "permalink": "/events/2015/2/21/the-church",
    "presented_by": null,
    "title": "The Church",
    "description": "Doors open: 20:30",
    "excerpt": "Doors open: 20:30",
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T20:30:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T20:30:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "FromCA$80.82",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1416419376/event-3353449.png", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3353449",
      "hover": "/t/h/e/3353449",
      "click": "/t/c/e/3353449/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3353449"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3353449",
      "hover": "https://t.dostuffmedia.com/t/h/e/3353449",
      "click": "https://t.dostuffmedia.com/t/c/e/3353449/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3353449"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17306,
      "title": "The Rio Theatre",
      "permalink": "/venues/the-rio-theatre",
      "latitude": 49.2621803,
      "longitude": -123.0704502,
      "popularity": 9.0,
      "address": "1660 East Broadway",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V5N 1W1",
      "full_address": "1660 East Broadway, Vancouver, BC, V5N 1W1",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }, {
    "id": 3425321,
    "permalink": "/events/2015/2/21/adham-shaikh-and-drumspyder",
    "presented_by": null,
    "title": "Adham Shaikh and Drumspyder",
    "description": "Doors open: 21:00\n<br />show with drumspyder. showcase some music from forthcoming album...",
    "excerpt": "Doors open: 21:00\nshow with drumspyder. showcase some music from forthcoming album...",
    "category": "Music",
    "category_param": "music",
    "conference_category_param": "",
    "begin_time": "2015-02-21T21:00:00-06:00",
    "tz_adjusted_begin_date": "2015-02-21T21:00:00-08:00",
    "tz_adjusted_end_date": "2015-02-22T02:00:00-08:00",
    "begin_date": "2015-02-21",
    "past": true,
    "end_date": null,
    "end_time": null,
    "votes": 0,
    "ticket_info": "",
    "allstar_votes": 0,
    "is_lens": false,
    "is_eventbrite": false,
    "eventbrite_id": null,
    "ticket_onsale_time": null,
    "tickets_onsale_today": false,
    "is_free": false,
    "is_ongoing": false,
    "imagery": {"photo": "v1418052722/event-3425321.png", "poster": ""},
    "rating": null,
    "doors": false,
    "tracking": {
      "impression": "/t/l/e/3425321",
      "hover": "/t/h/e/3425321",
      "click": "/t/c/e/3425321/http%3A%2F%2Fdostuffmedia.com%3A80%2Fevents%2F3425321"
    },
    "tracking_urls": {
      "impression": "https://t.dostuffmedia.com/t/l/e/3425321",
      "hover": "https://t.dostuffmedia.com/t/h/e/3425321",
      "click": "https://t.dostuffmedia.com/t/c/e/3425321/http%3A%2F%2Fdo604.com%3A80%2Fevents%2F3425321"
    },
    "popularity": 1.0,
    "sold_out": false,
    "favorite": false,
    "actions": {"add": true, "rsvp": false, "buy": false, "buy_vip": false, "win": false},
    "venue": {
      "id": 17263,
      "title": "Rickshaw Theatre",
      "permalink": "/venues/rickshaw-theatre",
      "latitude": 49.2809834,
      "longitude": -123.0983592,
      "popularity": 8.0,
      "address": "254 East Hastings St",
      "city": "Vancouver",
      "state": "BC",
      "zip": "V6A 1P1",
      "full_address": "254 East Hastings St, Vancouver, BC, V6A 1P1",
      "is_english": true
    },
    "artists": [],
    "rsvp": false,
    "eager": true
  }],
  "paging": {
    "entry_name": "events",
    "count": 7,
    "first": 1,
    "last": 7,
    "path": "/events/2015/02/21",
    "formatted_count": "7",
    "page_size": 25,
    "total_pages": 1,
    "current_page": 1,
    "offset_value": 0,
    "listing_ad_position": 12,
    "listing_ad_top_position": 3,
    "label": "Events"
  },
  "date": "2015-02-21",
  "timebands": [{"text": "02/21/15", "path": "/events/2015/02/21", "segment": null, "active": true}, {
    "text": "Today",
    "path": "/events/today",
    "segment": "today",
    "active": false
  }, {"text": "Tomorrow", "path": "/events/tomorrow", "segment": "tomorrow", "active": false}],
  "shortcuts": [{
    "text": "Music",
    "path": "/events/music",
    "segment": "music",
    "active": false
  }, {
    "text": "DJ / Parties",
    "path": "/events/dj-parties",
    "segment": "dj-parties",
    "active": false
  }, {
    "text": "Art & Culture",
    "path": "/events/art-culture",
    "segment": "art-culture",
    "active": false
  }, {"text": "Film", "path": "/events/film", "segment": "film", "active": false}, {
    "text": "Comedy",
    "path": "/events/comedy",
    "segment": "comedy",
    "active": false
  }, {
    "text": "Theatre & Performing Arts",
    "path": "/events/theatre-performing-arts",
    "segment": "theatre-performing-arts",
    "active": false
  }, {
    "text": "Food & Drink",
    "path": "/events/food-drink",
    "segment": "food-drink",
    "active": false
  }, {"text": "Sport & Wellness", "path": "/events/sport-wellness", "segment": "sport-wellness", "active": false}],
  "views": {"sort": "popularity", "mode": "list"},
  "heading_text": "What To Do in Vancouver on 02/21/15 ",
  "photos_base": "https://res.cloudinary.com/dostuff-media/image/upload/",
  "api_version": 0.005
}